name: Lighthouse (by URL)

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Full URL to audit:"
        required: true
        default: https://patlynk.com
        type: string
      runs:
        description: "Number of runs per form factor"
        required: false
        default: "3"
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo (not strictly needed, but nice to have)
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Lighthouse CI CLI
        run: npm i -g @lhci/cli@0.14.x

      - name: Create output folder
        run: mkdir -p ./lhci_reports

      # --- Desktop run ---
      - name: LHCI collect (desktop)
        run: |
          lhci collect \
            --url="${{ inputs.url }}" \
            --numberOfRuns=${{ inputs.runs }} \
            --settings.preset=desktop \
            --output-path=./lhci_reports/desktop.lhr.json \
            --json
      - name: LHCI upload (desktop)
        id: upload_desktop
        run: |
          set -e
          URL=$(lhci upload --target=temporary-public-storage --json=./lhci_reports/desktop.lhr.json | node -e "const d=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(d.lhrUrl||'');")
          echo "REPORT_URL=$URL" >> $GITHUB_OUTPUT

      # --- Mobile run ---
      - name: LHCI collect (mobile)
        run: |
          lhci collect \
            --url="${{ inputs.url }}" \
            --numberOfRuns=${{ inputs.runs }} \
            --settings.preset=mobile \
            --output-path=./lhci_reports/mobile.lhr.json \
            --json
      - name: LHCI upload (mobile)
        id: upload_mobile
        run: |
          set -e
          URL=$(lhci upload --target=temporary-public-storage --json=./lhci_reports/mobile.lhr.json | node -e "const d=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(d.lhrUrl||'');")
          echo "REPORT_URL=$URL" >> $GITHUB_OUTPUT

      # Optional: assert thresholds (tweak to your tolerance)
      - name: LHCI assert
        run: |
          lhci assert --assertions.preset "lighthouse:recommended" \
            --assertions.categories:performance=error \
            --assertions.categories:accessibility=warn \
            --assertions.categories:seo=warn \
            --assertions.categories:'best-practices'=warn || true
          # ^ keep `|| true` if you don't want failures to fail the workflow

      - name: Upload artifacts (full reports)
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lhci_reports
          retention-days: 7

      - name: Summarize
        run: |
          {
            echo "## Lighthouse reports"
            echo ""
            echo "- **URL:** ${{ inputs.url }}"
            echo "- **Desktop report:** ${{ steps.upload_desktop.outputs.REPORT_URL }}"
            echo "- **Mobile report:** ${{ steps.upload_mobile.outputs.REPORT_URL }}"
            echo ""
            echo "Download full JSON reports from the artifacts in this run."
          } >> $GITHUB_STEP_SUMMARY